[package]
name = "seedgen"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
bincode = { version = "2", features = ["derive"] }
wincode = { path = "../../../wincode" }
wincode-derive = { path = "../../../wincode-derive" }
